name: SonarCloud Analysis

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Install SonarScanner
        run: dotnet tool install --global dotnet-sonarscanner

      # ==========================
      # RESTORE
      # ==========================
      - name: Restore
        working-directory: ApiFinancas
        run: dotnet restore ApiFinancas.sln

      # ==========================
      # SONAR BEGIN
      # ==========================
      - name: Sonar Begin
        working-directory: ApiFinancas
        run: |
          dotnet sonarscanner begin \
            /k:"dmrogger_Api-Financas" \
            /o:"dmrogger" \
            /d:sonar.host.url="https://sonarcloud.io" \
            /d:sonar.cs.opencover.reportsPaths="**/coverage.opencover.xml"
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      # ==========================
      # BUILD
      # ==========================
      - name: Build
        working-directory: ApiFinancas
        run: dotnet build ApiFinancas.sln --no-restore --configuration Release

      # ==========================
      # SONAR END
      # ==========================
      - name: Sonar End
        working-directory: ApiFinancas
        run: dotnet sonarscanner end
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
